[.text-justify]
=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

Une fois notre idée fixée, nous avons approfondi nos recherches sur l’existence d’applications qui ressemblent à la nôtre sur le marché. Nous en sommes venus à classer les applications trouvées en deux catégories. D’une part, nous avons regroupé les applications ne favorisant pas directement la démocratie participative mais fonctionnant sur le même modèle que la nôtre. Comme E-cclesia, ces applications suggèrent à l’utilisateur des activités ou projets pouvant l’intéresser via un système de géolocalisation et lui permettent également de rechercher une activité ou un projet via un moteur de recherche intégré. C’est le cas par exemple de l’application Cultur’easy qui regroupe des activités culturelles. D’autre part, nous avons regroupé les applications ayant pour but d’augmenter la participation citoyenne mais ne fonctionnant pas selon notre modèle.  À ce sujet, dans le cadre des Civic Tech, de nombreuses start-ups se sont lancées dans le développement d’applications ayant pour ambition de renouveler la vie démocratique locale. On peut citer Vooter, City2Gether, Neocity, ou encore Fluicity.


<<CulturEasy, Cultur’easy>> : C’est une application dont le développement a été motivé par le manque de visibilité sur les activités culturelles qui se passent autour de nous. Le but de cette application est de permettre à l’utilisateur d’accéder plus facilement à la culture en l’accompagnant au quotidien. Comme notre application, Cultur’easy utilise la géolocalisation pour suggérer à l’utilisateur des activités culturelles et lui propose aussi un moteur de recherche suggestif et personnalisé s’il a envie de s’intéresser à une activité en particulier. Notre application proposera en plus des notifications configurables et un bilan quotidien. Concernant le côté social de Cultur’easy, elle met en place une zone d’expression vidéo pour le partage d’expériences et de bandes-annonces culturelles. Ceci serait différent dans notre application, qui se basera davantage sur le principe d’un réseau social où il sera par exemple possible de partager des projets à ses amis.

<<BudgetParticipatif, Site Budget Participatif Paris>> : C’est un site où les parisiens et parisiennes peuvent proposer et/ou suivre des projets basés sur le processus de démocratie participative. En effet, la ville de Paris alloue 5% du budget d’investissement dans des projets à l’initiative de ses habitants. Les projets proposés sont examinés par la ville de Paris pour déterminer leur recevabilité et leur faisabilité. Ils sont ensuite soumis à un vote et les projets avec le plus de voix auront la chance d’être concrétisés. Ce qui est proposé par la ville de Paris est dans le même esprit que ce que nous voulons proposer, à savoir favoriser plus de participation citoyenne, même si notre application n’a pas pour but principal de favoriser le vote des projets mais plutôt d’informer sur les projets existants et sur les manières possibles de s’y impliquer. Seulement, le problème d’un site Internet est que cela rend les projets moins visibles de la majorité. C’est pourquoi nous pensons qu’une application simplifiant l’accès aux projets donnerait à ceux-ci une certaine visibilité. Pour les municipalités voulant mettre en place un budget participatif, c’est d’ailleurs ce que propose la start-up Fluicity.

<<Fluicity, Fluicity>> : C’est une start-up développant une application mobile et un portail web qui s’adresse aux élus et aux services voulant mettre en place un budget participatif pour favoriser la participation citoyenne. Ces plateformes permettent aux citoyens de soumettre leurs idées au vote des autres citoyens, de participer à des projets autours de sujets propres aux collectivités, ou de répondre à des sondages lancés à l’initiative des acteurs locaux. Notre application veut aussi proposer aux utilisateurs de participer à des projets citoyens et sociaux, mais ne fonctionne pas comme Fluicity, elle se basera sur un système de géolocalisation pour informer l’utilisateur des projets autour de lui. 


Somme toute, aucune des applications présentées ne correspond à celle que nous voudrions créer. Mais E-cclesia s’inspire de chacune d’elles pour suggérer à la fois des projets citoyens, sociaux et culturels directement à l’utilisateur. 