[.text-justify]
=== Description de la proposition

Lors de la recherche de notre sujet, différents sujets de société ont particulièrement retenu notre attention. Nous avons hésité entre le thème de la santé connectée et celui de la démocratie participative. Sur chacun des deux sujets, nous nous sommes longuement interrogés sur l’état de l’art et sur le degré d’innovation que nous pouvions apporter. Concernant le thème de la santé connectée, nous étions partis sur la conception de lunettes connectées pour aider les personnes malvoyantes à se déplacer en milieu urbain. Mais ce que nous voulions faire existait déjà, d’autant plus que nous aurions dû revoir nos objectifs à la baisse et nous concentrer seulement sur un type d’obstacle précis si nous voulions réaliser quelque chose de concret. Nous avons donc laissé cette idée de côté. Concernant le deuxième sujet de société qui a retenu notre attention, nous sommes partis d’une volonté : celle de promouvoir davantage la démocratie participative. On peut constater au quotidien que la grande majorité des citoyens ne participent pas vraiment à la vie démocratique car nous nous sentons de moins en moins concernés par les décisions prises par nos élus. En effet, un simple nombre permet d’illustrer cela : 58,4%, c’est le taux d’abstention au second tour des élections municipales, communautaires et métropolitaines 2020. De fait, chacun se recentre sur sa sphère privée en se tenant informé de l’actualité principalement via les réseaux sociaux et les applications de son smartphone. 

Partant de cette volonté, nous avons d’abord pensé à créer une application de débat participatif qui faciliterait les échanges entre élus et citoyens afin que les citoyens puissent participer davantage aux prises de décisions et se sentir plus concernés par celles-ci. Mais après quelques recherches, nous avons constaté qu’il en existait déjà quelques unes. De plus, une telle application aurait été compliquée à mettre en œuvre concrètement car il aurait fallu que des députés ou des acteurs locaux acceptent de participer à notre projet. Nous avons donc creusé en profondeur pour chercher d’autres idées tournant autour de la démocratie participative. Nous nous sommes alors demandés la question suivante : Pourquoi arrivons-nous à un point où il devient nécessaire de promouvoir la participation citoyenne ? Les causes sont nombreuses mais un constat majeur est ressorti de notre discussion : le manque cruel de visibilité sur les projets citoyens qui peuvent exister.

Notre idée avec E-cclesia est donc de faciliter l’accès aux projets citoyens et sociaux autour de son environnement. Pour faciliter au maximum l’information, nous pensons que le plus efficace est d’utiliser un système de géolocalisation pour indiquer à l’utilisateur les projets ayant lieu autour de son lieu de vie ou sur ses trajets quotidiens. Un algorithme personnalisé interne à l’application permettra d’affiner les propositions pour lui suggérer des projets susceptibles de l'intéresser. Si l’utilisateur souhaite chercher un projet, un lieu ou un thème en particulier, E-cclesia proposera également une barre de recherche pour cela. Dans un second temps, nous nous sommes dit qu’il serait également intéressant de ne pas seulement se limiter aux projets citoyens et sociaux mais d’y ajouter les projets culturels. En effet, les activités culturelles font aussi vivre la vie sociale et donc nous permettent d’échanger avec les autres, d’élargir nos horizons.

De plus, toujours dans l’idée de vouloir inciter les citoyens à s’impliquer davantage dans la vie démocratique et citoyenne, nous voulons inclure à E-cclesia une dimension sociale, qui fonctionnerait sur le principe d’un réseau social interne où les différents utilisateurs peuvent se partager des projets et peuvent suivre les autres. 

L’exercice “pour/contre” effectué lors d’une séance PACT nous a aiguillé pour définir les différentes tâches que devrait inclure E-cclesia. En nous mettant dans la position de quelqu’un qui défend le projet puis de quelqu’un qui s’oppose au projet, nous avons ainsi pu ajouter les fonctionnalités manquantes et en modifier certaines. 