=== Contexte

Camille est une mère célibataire de deux enfants en bas âge. Sa journée type est très chargée entre ses enfants à accompagner à l’école puis son trajet jusqu’à son travail en voiture, son job, le retour, les courses, le ménage... Le soir elle a juste le temps de s’occuper de ses enfants et s’endort souvent devant les informations télévisées, elle n’a pas vraiment de disponibilités pour chercher sur Internet ce qu’elle aime. Car si son quotidien est rythmé par sa vie professionnelle et sa famille, qu’elle adore, sa vie citoyenne manque à l’appel ! Elle se souvient lorsque, adolescente, elle manifestait pour le mariage pour tous et distribuait des tracts du parti communiste. Cette époque, cette implication, lui manquent et elle aimerait faire plus pour s’engager et soutenir des actions qui lui tiennent à cœur malgré son quotidien chargé. Via un collègue de bureau très actif sur des projets sociaux Camille entend parler ce cette super application qui te propose plein de projets. Elle décide de la découvrir et la télécharge. 

=== Prise en main

Pour en devenir utilisatrice, il lui suffit de se créer un compte. Quelques clics et c’est fait. L’application lui propose ensuite un questionnaire de personnalisation afin de savoir quels sont ses goûts (films, dans quels types d’actions associatives elle souhaite s’engager) et de savoir quels projets l’application doit mettre en avant mais aussi dans quelles villes elle souhaite s’impliquer et découvrir des choses. L’application lui demande aussi à quelle fréquence elle souhaite être notifiée de nouveaux projets. 

=== Utilisation de l'application

Une fois ses critères personnels saisis, Camille ouvre l’application : elle arrive alors sur une carte qui la géolocalise et montre des bulles tout autour d’elle, à chaque endroit où des projets qui pourraient l’intéresser sont en cours. L’application a recherché automatiquement sur Internet des projets grâce à des techniques de recherches de données (APIs ou scraping), les a triés dans une base de données, et y a sélectionné les projets se rapprochant le plus de ses goûts. En cliquant sur une bulle, elle accède à la liste des projets, puis en cliquant sur le nom de l’un d’entre eux, elle accède à la description du projet. En bas de la description, il y a un bouton unique et un lien vers le site associé. Lorsqu’elle clique sur le lien, la page du site s’ouvre dans l’application, et elle peut la refermer pour retourner sur le descriptif du projet. Lorsqu’elle appuie sur le bouton unique, il y a quatre propositions qui s’affichent : « ça m’intéresse » et « peut-être », qui placent ce projet dans la sous rubrique associée de la rubrique « Mes projets », « ça ne m’intéresse pas », qui enlève la suggestion, et « envoyer à » qui propose à Camille de partager ce projet avec ses contacts. Pour faciliter cette dernière action, elle pourra synchroniser ses amis Facebook en se connectant sur Facebook à partir de l'application. En fonction de la manière dont Camille interagit avec les projets qui lui sont proposés, l’algorithme de l’application retient ses préférences et lui propose des recommandations personnalisées, susceptibles de l’intéresser. 

Lorsque Camille souhaite chercher un projet ou un lieu spécifique, elle peut utiliser la barre de recherche de l’application en entrant des mots clés, ce qui lui affichera une liste de projets associés à sa recherche. Elle aura également la possibilité de liker ses lieux favoris, et l’algorithme de recommandation en tiendra compte par la suite. 

Avec ses journées sont très chargées, elle n’a pas toujours le temps de découvrir les projets sur le moment. Dans ce cas, à la fin de sa journée, elle reçoit un bilan actualisé des projets via une notification dont elle a programmé l’horaire. Elle est souvent surprise de découvrir les projets culturels, de société ou d’aménagement urbain qui sont en cours dans sa ville. Quand elle n’a pas ouvert son application depuis plusieurs jours, elle peut avoir accès à l’historique des projets qui se sont déroulés à proximité. Ce soir, elle découvre des suggestions de pièce de théâtre pour enfants et se dit qu’elle pourrait y emmener ses enfants pour changer du cinéma…
